// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqRe4yXRlczMV7i7ypBtd6hg4zzlbZb4U',
    appId: '1:690080842037:web:173106edce0ad2191b0c7c',
    messagingSenderId: '690080842037',
    projectId: 'inventory-app-8ec76',
    authDomain: 'inventory-app-8ec76.firebaseapp.com',
    storageBucket: 'inventory-app-8ec76.firebasestorage.app',
    measurementId: 'G-2041MT6YTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8LWYt7qQaw_i9VH2rNdWLpE5ez09uHD8',
    appId: '1:690080842037:android:f1ca952856a014a41b0c7c',
    messagingSenderId: '690080842037',
    projectId: 'inventory-app-8ec76',
    storageBucket: 'inventory-app-8ec76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGcwTepQvtftOmHIHCRUNlWY9g7D5nFDo',
    appId: '1:690080842037:ios:a85f68b9f2b791cd1b0c7c',
    messagingSenderId: '690080842037',
    projectId: 'inventory-app-8ec76',
    storageBucket: 'inventory-app-8ec76.firebasestorage.app',
    iosBundleId: 'com.example.ica15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGcwTepQvtftOmHIHCRUNlWY9g7D5nFDo',
    appId: '1:690080842037:ios:a85f68b9f2b791cd1b0c7c',
    messagingSenderId: '690080842037',
    projectId: 'inventory-app-8ec76',
    storageBucket: 'inventory-app-8ec76.firebasestorage.app',
    iosBundleId: 'com.example.ica15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqRe4yXRlczMV7i7ypBtd6hg4zzlbZb4U',
    appId: '1:690080842037:web:ad3ca2e6f2f3ef2c1b0c7c',
    messagingSenderId: '690080842037',
    projectId: 'inventory-app-8ec76',
    authDomain: 'inventory-app-8ec76.firebaseapp.com',
    storageBucket: 'inventory-app-8ec76.firebasestorage.app',
    measurementId: 'G-C32SL85PNL',
  );
}
